"""add apply_links jsonb to job_postings

Revision ID: 9d9ae9f26286
Revises: 9ffc8d1bf946
Create Date: 2026-04-02 13:00:37.698787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d9ae9f26286'
down_revision: Union[str, Sequence[str], None] = '9ffc8d1bf946'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_postings', sa.Column('apply_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_postings', 'apply_links')
    # ### end Alembic commands ###
