"""initial tables profiles and job_postings

Revision ID: 9ffc8d1bf946
Revises: 
Create Date: 2026-03-31 13:49:07.003418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ffc8d1bf946'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('resume_pdf_path', sa.String(), nullable=False),
    sa.Column('resume_text', sa.Text(), nullable=True),
    sa.Column('target_queries', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('target_locations', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('evaluator_prompt', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_postings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('job_url', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('match_reasoning', sa.Text(), nullable=True),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('application_status', sa.String(), nullable=False),
    sa.Column('search_query', sa.String(), nullable=True),
    sa.Column('date_added', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_evaluated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'job_url', name='uq_profile_job_url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_postings')
    op.drop_table('profiles')
    # ### end Alembic commands ###
